listener 1883 0.0.0.0
protocol mqtt
listener_allow_anonymous true

listener 9001 0.0.0.0
protocol websockets
listener_allow_anonymous false
password_file /mosquitto/config/passwords

connection aws-iot
address a2ie1b3xp2emgi-ats.iot.ap-northeast-2.amazonaws.com:8883
bridge_protocol_version mqttv311
remote_clientid mosquitto-bridge
try_private false
notifications false
cleansession true
start_type automatic
restart_timeout 5

bridge_cafile /mosquitto/config/certs/AmazonRootCA1.pem
bridge_certfile /mosquitto/config/certs/mosquitto-bridge.cert.pem
bridge_keyfile /mosquitto/config/certs/mosquitto-bridge.private.key

topic sensimul/sites/# out 1