name: StockOps MSA Production EKS & CloudFront CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  EKS_CLUSTER_NAME: seoul-cluster
  ECR_REGISTRY: 448768137813.dkr.ecr.ap-northeast-2.amazonaws.com

jobs:
  deploy:
    name: Build, Push and Deploy to EKS & S3/CloudFront
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::448768137813:role/github-actions-ecr-push
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Node.js Environment
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Build & Deploy Client Web to S3
      env:
        S3_CLIENT_BUCKET: siseon-frontend-client
      run: |
        cd ./stockops-client-web
        npm install
        npm run build
        aws s3 sync ./dist s3://$S3_CLIENT_BUCKET --delete

    - name: Build & Deploy Admin Web to S3
      env:
        S3_ADMIN_BUCKET: siseon-frontend-admin
      run: |
        cd ./stockops-admin-web
        npm install
        npm run build
        aws s3 sync ./dist s3://$S3_ADMIN_BUCKET --delete

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Backend Images to Amazon ECR
      run: |
        docker build -t $ECR_REGISTRY/stockops-api:latest ./stockops-api-server
        docker push $ECR_REGISTRY/stockops-api:latest
        
        docker build -t $ECR_REGISTRY/stockops-ai:latest ./stockops-ai-module
        docker push $ECR_REGISTRY/stockops-ai:latest

    - name: Set up Kubeconfig Context for Amazon EKS
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

    - name: Deploy & Rollout Restart to Amazon EKS Cluster
      run: |
        kubectl rollout restart deployment/stockops-api -n stockops
        kubectl rollout restart deployment/stockops-ai -n stockops

    - name: CloudFront Cache Invalidation
      run: |
        CLIENT_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@=='siseon.live']].Id" --output text)
        ADMIN_DIST_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Aliases.Items[?@=='app.siseon.live']].Id" --output text)
        
        aws cloudfront create-invalidation --distribution-id $CLIENT_DIST_ID --paths "/*"
        aws cloudfront create-invalidation --distribution-id $ADMIN_DIST_ID --paths "/*"